file_format: "1"
id: skelety_rene
name: Skeletyl Rene
type: shield
url: https://gitlab.com/rspecius/skeletyl_rene/
requires: [2 x nrfmicro]
features:
  - keys
  - wireless
  - split
  siblings:
  - skeletyl_rene_left
  - skeletyl_rene_right
